base:
  build: .
  dockerfile: Dockerfile
  command: bash
  volumes:
  - "$PWD/src:/src"

tests:
  extends:
    file: docker-compose.yml
    service: base
  command: py.test -v --capture=sys --cov-report term --cov-report html --cov-report xml --junitxml /out/TEST-all.xml --cov rockman rockman_tests
  volumes:
    - "$PWD/out:/out"

pep8:
  extends:
    file: docker-compose.yml
    service: base
  command: flake8 --output-file=/out/flake8.txt rockman/
  volumes:
    - "$PWD/out:/out"

rockman:
  extends:
    file: docker-compose.yml
    service: base
  command: django-admin runserver 0.0.0.0:8000
  volumes:
  - "$PWD/data:/data"
  ports:
  - 80:8000
